Enable TypeScript strict mode + fix up issues
nornagon/flatten-svg pull request #17
Opened 2022-05-06 07:58 UTC by akx

Originally from #14.

This PR:

* enables `strict` and fixes up some problems uncovered by it
* moves the `ang()` inner function to a free function
* fixes up some unnecessary variable reassignment/aliasing

2022-05-08 00:05 UTC, nornagon requested changes

2022-05-08 00:05 UTC, nornagon commented on src/svg-to-paths.ts
> +          stroke: getStroke(shape) ?? undefined,
`?? undefined` makes no sense to me... return undefined unless the value is undefined?

2022-05-08 00:05 UTC, nornagon commented on src/svg-to-paths.ts
> +        if(cur === null) {
```suggestion
        if (cur === null) {
```

2022-05-08 00:05 UTC, nornagon commented on src/svg-to-paths.ts
> +          throw new Error(`C ${cmd} encountered without current point`)
`cmd` is an object here right? Won't this show `C [object Object] ...`?

2022-05-08 00:05 UTC, nornagon commented on src/svg-to-paths.ts
> +        if(cur === null) {
```suggestion
        if (cur === null) {
```

2022-05-08 00:05 UTC, nornagon commented on src/svg-to-paths.ts
> +        if(cur === null) {
same here

2022-05-09 05:02 UTC, akx commented on src/svg-to-paths.ts
> +          stroke: getStroke(shape) ?? undefined,
`??` also defers to the right-hand side of the operator if the left side is `null`. `getStroke()` returns `string | null`, but `Line` defines `stroke` as `stroke?: string;`, so we need to turn that `null` into `undefined` (or change `Line`'s type).

2022-05-09 05:05 UTC, akx commented on src/svg-to-paths.ts
> +          throw new Error(`C ${cmd} encountered without current point`)
Good catch! Changing that to `cmd.values`.

Just needed to add some `throw` here so the type of  `cur` gets narrowed to non-null, didn't think about the message too closely.

2022-05-09 05:10 UTC, akx commented on src/svg-to-paths.ts
> +          throw new Error(`C ${cmd} encountered without current point`)
On that note, I'll give

https://github.com/nornagon/flatten-svg/blob/6d6cde877e028381def7cc488c2609208ebc50bc/src/svg-to-paths.ts#L239

the same treatment 😁

2022-05-09 23:02 UTC, nornagon commented on src/svg-to-paths.ts
> +          stroke: getStroke(shape) ?? undefined,
We should either change `getStroke` to return `string | undefined` or change `Line` to have the type `string | null`.

2022-05-09 23:03 UTC, nornagon commented
LGTM except for the `undefined` / `null` nitpick!

2022-05-10 05:14 UTC, akx commented on src/svg-to-paths.ts
> +          stroke: getStroke(shape) ?? undefined,
@nornagon I changed `getStroke` and `getGroupId` to return `undefined` instead of `null`. 👍

2022-05-10 22:35 UTC, nornagon approved these changes

2022-05-10 22:35 UTC, merged